volumes:
  database_data:

networks:
  kitty_network:
    external: false
    name: '${DOCKER_NETWORK:-kitty_network}'
    driver: bridge

services:
  database:
    image: postgres:16.3-alpine
    container_name: database
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432
    networks:
      - kitty_network
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
